sudo: required
services:
  - docker

before_install:
  - docker build -t chrishalley/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run chrishalley/react-test yarn run test -- --coverage

after_success:
  - docker build -t chrishalley/multi-client ./client
  - docker build -t chrishalley/multi-nginx ./nginx
  - docker build -t chrishalley/multi-server ./server
  - docker build -t chrishalley/multi-worker ./worker

  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin

  - docker push chrishalley/multi-client
  - docker push chrishalley/multi-nginx
  - docker push chrishalley/multi-server
  - docker push chrishalley/multi-worker