sudo: required
services:
  - docker

before_install:
  - docker build -t chrishalley86/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chrishalley86/react-test npm test

after_success:
  - docker build -t chrishalley86/multi-client ./client
  - docker build -t chrishalley86/multi-nginx ./nginx
  - docker build -t chrishalley86/multi-server ./server
  - docker build -t chrishalley86/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push chrishalley86/multi-client
  - docker push chrishalley86/multi-nginx
  - docker push chrishalley86/multi-server
  - docker push chrishalley86/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-597059939459
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY