apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cibolo-co-uk-tls
spec:
  secretName: cibolo-co-uk
  issuerRef:
    name: letencrypt-prod
    kind: ClusterIssues
  commonName: cibolo.co.uk
  dnsNames:
    - cibolo.co.uk
    - www.cibolo.co.uk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - cibolo.co.uk
          - www.cibolo.co.uk
      